# Site settings
title: Lille Web
email: contact@lille-web.fr
description: "Retrouvez les dernières tendances du web : articles, conférences, formations, tout ce dont vous avez besoin, pour et par des passionnés ! Retrouvez nous sur twitter : @lille_web "
baseurl: ""
url: "http://lilleweb.fr"
twitter_username: lille_web
github_username:  jekyll
paginate: 5
paginate_path: "articles/page:num"

# Build settings
markdown: kramdown
permalink: pretty
sass:
  style: compressed
  sass_dir: _sass
sitemap:
    file: "/sitemap.xml"
    exclude:
        - "/atom.xml"
        - "/feed.xml"
        - "/feed/index.xml"
        - "/data.json"
    include_posts:
        - "/index.html"
    change_frequency_name: "daily"
    priority_name: "0.8"
