# Site settings
title: Lille Web
email: contact@lille-web.fr
baseurl: ""
url: "http://lille-web.fr"
twitter_username: lille_web
github_username:  jekyll
paginate: 5
paginate_path: "articles/page:num"

# Build settings
markdown: kramdown
permalink: pretty
sass:
  style: compressed
  sass_dir: _sass
