# Site settings
title: Lille Web
email: contact@lille-web.fr
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
baseurl: ""
url: "http://lille-web.fr"
twitter_username: lille_web
github_username:  jekyll
paginate: 5
paginate_path: "articles/page:num"

# Build settings
markdown: kramdown
permalink: pretty
sass:
  style: compressed
  sass_dir: _sass
